package net.projecteuler;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Problem 2: Even Fibonacci Numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence that do not exceed the nth term, find the sum of the
 * even-valued terms.
 */
public class Problem02Spec {

    // original tests
    @Test
    public void given_10Return_44(){
    }
    @Test
    public void given_18Return_3382(){
    }
    @Test
    public void given_23Return_60696(){
    }
    @Test
    public void given_43Return_350704366(){
    }

}
